---
- name: 
  hosts: webserver
  tasks:
  - name: Debug - out host_os_family
    debug: msg={{ ansible_os_family }}

  - name: Install httpd package
    yum: name=httpd state=latest
    become: true
    when: ansible_os_family == "RedHat"

  - name: Install apache2 package
    apt: name=apache2 state=latest
    become: true
    when: ansible_os_family == "Debian"

  - name: enable proxy
    apache2_module: name=proxy state=present
    become: true
    notify:
      - restart apache2

  - name: enable headers
    apache2_module: name=headers state=present
    become: true
    notify:
      - restart apache2

  - name: enable proxy_http
    apache2_module: name=proxy_http state=present
    become: true
    notify:
      - restart apache2

  - name: copy jenkinx redirect config
    copy:
      src: ./webserver-data/site-jenkins.tar.gz
      dest: /tmp/site-jenkins.tar.gz
    become: true

    

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
      become: true