---
# file: provision.yml
- name: Provision webservers
  hosts: webservers
  tags: web

  tasks:
    - name: Include vars
      include_vars:
        dir: roles/java/defaults

    - name: out variants
      debug: var=item
      loop:
        "{{ java_urls |dict2items }}"

    - name: out fixed
      debug: 
        msg: "URL: {{ java_urls['jdk-8u201'].name }}"

    - name: download package
      command: "wget --continue --no-check-certificate -O /tmp/{{ java_urls['jdk-8u201'].name }}-linux-x64.tar.gz --header 'Cookie: oraclelicense=a' {{ java_urls['jdk-8u201'].url }}"
      args: 
        creates: /tmp/{{ java_urls['jdk-8u201'].name }}-linux-x64.tar.gz

    - name: ansible create directory example
      file:
        path: /usr/lib/jvm
        state: directory

    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /tmp/{{ java_urls['jdk-8u201'].name }}-linux-x64.tar.gz
        dest: /usr/lib/jvm
        remote_src: yes

#wget --continue --no-check-certificate -O jdk-8u191-linux-x64.tar.gz --header "Cookie: oraclelicense=a" https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.tar.gz
