---
# file: provision.yml
- name: Fix permissions to ssh private key file
  hosts: all
  gather_facts: no
  tasks:
    - name: Fix devops.pem permission after Git
      delegate_to: localhost  
      run_once: true
      file:
        path: "{{ devops_private_ssh_key }}"
        mode: 0600


- name: Provision webservers
  hosts: webservers
  tags: web
  vars:
    user2: 
      _name: "devops"
      _authorized_keys: ["files/devops.pub"]
      _groups: ["sudo"]
      _shell: "/bin/bash"
      _sudoline: "devops ALL=(ALL) NOPASSWD: ALL"  

  pre_tasks:
    - name: Some pre_tasks
      shell: echo 'I":" Beginning to configure web server..'
      delegate_to: localhost
      changed_when: false

  roles:
    - common
    - role: adduser
      vars:
        user: "{{ user2 }}"
    - httpd

  post_tasks:
    - name: Some post_tasks
      shell: echo 'I":" Done configuring web server..'
      delegate_to: localhost
      changed_when: false


- name: Provision appservers
  hosts: appservers
  tags: app

  pre_tasks:
    - name: Some pre_tasks
      shell: echo 'I":" Beginning to configure app server..'
      changed_when: false
      delegate_to: localhost

  roles:
    - common
    - devops_user  
    - java
    - jenkins
    
  post_tasks:
    - name: Some post_tasks
      shell: echo 'I":" Done configuring app server..'  
      changed_when: false
      delegate_to: localhost

