nodes = [
  { :name => 'webserver', 
    :ip => '192.168.10.10', 
    :ssh_port => '4022', 
    :web_port => '4080', 
    :web2_port => '4088' 
  },
  { :name => 'appserver', 
    :ip => '192.168.10.11', 
    :ssh_port => '4122', 
    :web_port => '4180', 
    :web2_port => '4188' 
  },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:name] do |nodeconfig|
      nodeconfig.vm.box = "ubuntu/bionic64"
      nodeconfig.vm.box_check_update = false
      nodeconfig.ssh.insert_key = false
      nodeconfig.vm.hostname = node[:name]
      nodeconfig.vm.network :private_network, ip: node[:ip]
      nodeconfig.vm.network :forwarded_port, guest: 22, host: node[:ssh_port], id: "sshAll", auto_correct: true
      nodeconfig.vm.network :forwarded_port, guest: 80, host: node[:web_port], id: "webAll", auto_correct: true
      nodeconfig.vm.network :forwarded_port, guest: 8080, host: node[:web2_port], id: "web2All", auto_correct: true
      #nodeconfig.vm.network "public_network", bridge: "wlp3s0", use_dhcp_assigned_default_route: true
      nodeconfig.vm.provision "ansible" do |ansible|
        #ansible.verbose = "vvv"      
        ansible.compatibility_mode = '2.0'        
        ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
        ansible.playbook = "vagrant-bootstrap.yml"
        ansible.host_vars = {
          node[:name] => {"direct_ssh_port" => node[:ssh_port],
                          "private_ip" => node[:ip]}
        }        
      end
    end
  end
end

