---
# file: main.yml (tasks-httpd-roles)
- name: Define httpd_packages
  set_fact:
    httpd_packages: "{{ def_httpd_packages | list }}"
  when: httpd_packages is not defined

- name: Define httpd_modules
  set_fact:
    httpd_modules: "{{ def_httpd_modules | list }}"
  when: httpd_modules is not defined

- name: Install OS packages
  become: true
  apt: 
    name: "{{ httpd_packages }}"
    state: latest  
    update_cache: true    

- name: Enable apache modules
  become: true  
  apache2_module: 
    name: "{{ item }}"
    state: present  
  loop: "{{ httpd_modules }}"
  notify:
    - restart apache2
