---
# file: main.yml (tasks-jenkins-roles)
- name: Installing Jenkins
  include_tasks: jenkins_install.yml
  when: ansible_local.provision.general.jenkins is not defined

- name: Parse init password jenkins
  become: true    
  tags: initkey
  shell: cat {{ jenkins_home }}/.jenkins/secrets/initialAdminPassword
  changed_when: false
  register: jnkInitPass

- name: Print init password jenkins
  tags: initkey
  debug: 
    var: jnkInitPass.stdout  
