---
# file: provision.yml
- name: Fix permissions to ssh private key file
  hosts: all
  gather_facts: no
  tasks:
    - name: Fix devops.pem permission after Git
      delegate_to: localhost  
      run_once: true
      file:
        path: "{{ devops_private_ssh_key }}"
        mode: 0600

- name: Provision webservers
  hosts: webservers
  tags: web
  roles:
    - devops_user  
    - httpd
    - java
  