---
# file: provision.yml
- name: Fix permissions to ssh private key file
  hosts: all
  gather_facts: no
  tasks:
    - name: Fix devops.pem permission after Git
      delegate_to: localhost  
      run_once: true
      file:
        path: "{{ devops_private_ssh_key }}"
        mode: 0600

- name: Provision webservers
  hosts: webservers
  tags: web
  pre_tasks:
    - shell: echo 'I":" Beginning to configure web server..'
  roles:
    - devops_user  
    - httpd
  post_tasks:
     - shell: echo 'I":" Done configuring web server..'

- name: Provision appservers
  hosts: appservers
  tags: app
  pre_tasks:
  - shell: echo 'I":" Beginning to configure app server..'
  roles:
    - devops_user  
    - java
    - jenkins
  post_tasks:
     - shell: echo 'I":" Done configuring app server..'  
